Repository fsr5-fhaachen/portals, pull requests merged in 2022-08, with the labels that each got.

#29 Add workflows
  .github/ workflows/node.js.yml
  .github/ workflows/php.yml
  .github/dependabot.yml
  .github/release.yml
Labels: enhancement

#43 General improvements
  .github/workflows/node.js.yml
  .github/workflows/php.yml
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: enhancement

#48 Merge dev to main
  .github/workflows/node.js.yml
  .github/workflows/php.yml
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: enhancement

#59 Add ignore-platform-reqs argument
  .github/workflows/php.yml
Labels: bug

#61 Fix argument
  .github/workflows/php.yml
Labels: bug

#62 Try another fix
  .github/workflows/php.yml
Labels: bug

#63 erd
  docs/erd/README.md
  docs/erd/erd.dmm
  docs/erd/erd.pdf
  docs/erd/html/allOf-dark.svg
  docs/erd/html/allOf-light.svg
  docs/erd/html/anyOf-dark.svg
  docs/erd/html/anyOf-light.svg
  docs/erd/html/assets/ak.svg
  docs/erd/html/assets/fk.svg
  docs/erd/html/assets/ik.svg
  docs/erd/html/assets/im-line-icons.eot
  docs/erd/html/assets/im-line-icons.svg
  docs/erd/html/assets/im-line-icons.ttf
  docs/erd/html/assets/im-line-icons.woff
  docs/erd/html/assets/index.svg
  docs/erd/html/assets/inter.svg
  docs/erd/html/assets/linked.svg
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-600.eot
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-600.svg
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-600.ttf
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-600.woff
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-600.woff2
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-700.eot
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-700.svg
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-700.ttf
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-700.woff
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-700.woff2
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-regular.eot
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-regular.svg
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-regular.ttf
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-regular.woff
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-regular.woff2
  docs/erd/html/assets/pfk.svg
  docs/erd/html/assets/pk.svg
  docs/erd/html/assets/union.svg
  docs/erd/html/assets/watermark-meteor.svg
  docs/erd/html/assets/watermark-moon.svg
  docs/erd/html/assets/watermark-perseid.svg
  docs/erd/html/datensen-moon-modeler-report.css
  docs/erd/html/else-dark.svg
  docs/erd/html/else-light.svg
  docs/erd/html/if-dark.svg
  docs/erd/html/if-light.svg
  docs/erd/html/im.css
  docs/erd/html/index.html
  docs/erd/html/lists.css
  docs/erd/html/modals.css
  docs/erd/html/not-dark.svg
  docs/erd/html/not-light.svg
  docs/erd/html/oneOf-dark.svg
  docs/erd/html/oneOf-light.svg
  docs/erd/html/scrollbars.css
  docs/erd/html/searchbar.css
  docs/erd/html/style.css
  docs/erd/html/then-dark.svg
  docs/erd/html/then-light.svg
Labels: documentation, enhancement

#64 Merge main to dev
  .github/workflows/node.js.yml
  .github/workflows/php.yml
  composer.json
  composer.lock
  docs/erd/README.md
  docs/erd/erd.dmm
  docs/erd/erd.pdf
  docs/erd/html/allOf-dark.svg
  docs/erd/html/allOf-light.svg
  docs/erd/html/anyOf-dark.svg
  docs/erd/html/anyOf-light.svg
  docs/erd/html/assets/ak.svg
  docs/erd/html/assets/fk.svg
  docs/erd/html/assets/ik.svg
  docs/erd/html/assets/im-line-icons.eot
  docs/erd/html/assets/im-line-icons.svg
  docs/erd/html/assets/im-line-icons.ttf
  docs/erd/html/assets/im-line-icons.woff
  docs/erd/html/assets/index.svg
  docs/erd/html/assets/inter.svg
  docs/erd/html/assets/linked.svg
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-600.eot
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-600.svg
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-600.ttf
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-600.woff
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-600.woff2
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-700.eot
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-700.svg
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-700.ttf
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-700.woff
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-700.woff2
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-regular.eot
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-regular.svg
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-regular.ttf
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-regular.woff
  docs/erd/html/assets/open-sans-v17-latin-ext_latin-regular.woff2
  docs/erd/html/assets/pfk.svg
  docs/erd/html/assets/pk.svg
  docs/erd/html/assets/union.svg
  docs/erd/html/assets/watermark-meteor.svg
  docs/erd/html/assets/watermark-moon.svg
  docs/erd/html/assets/watermark-perseid.svg
  docs/erd/html/datensen-moon-modeler-report.css
  docs/erd/html/else-dark.svg
  docs/erd/html/else-light.svg
  docs/erd/html/if-dark.svg
  docs/erd/html/if-light.svg
  docs/erd/html/im.css
  docs/erd/html/index.html
  docs/erd/html/lists.css
  docs/erd/html/modals.css
  docs/erd/html/not-dark.svg
  docs/erd/html/not-light.svg
  docs/erd/html/oneOf-dark.svg
  docs/erd/html/oneOf-light.svg
  docs/erd/html/scrollbars.css
  docs/erd/html/searchbar.css
  docs/erd/html/style.css
  docs/erd/html/then-dark.svg
  docs/erd/html/then-light.svg
Labels: bug, documentation, enhancement, dependencies

#65 Move to vite and fix small bugs
  .editorconfig
  .env.example
  .github/workflows/php.yml
  composer.json
  composer.lock
  package-lock.json
  package.json
  resources/js/App.vue
  resources/js/Pages/Admin/Index.vue
  resources/js/Pages/Admin/Result.vue
  resources/js/Pages/Admin/Start.vue
  resources/js/Pages/Index.vue
  resources/js/Pages/Login.vue
  resources/js/Pages/Tutor/Group/Index.vue
  resources/js/Pages/Tutor/Overview.vue
  resources/js/Pages/Tutor/Station/Index.vue
  resources/js/app.js
  resources/views/app.blade.php
  vite.config.js
  webpack.mix.js
Labels: bug, enhancement, breaking-change

#72 Update erd
  docs/erd/erd.dmm
  docs/erd/erd.pdf
  docs/erd/html/index.html
Labels: documentation, enhancement

#80 Feat/esa feedback
  docs/erd/erd.dmm
  docs/erd/erd.pdf
  docs/erd/html/index.html
Labels: documentation, enhancement

#87 Made requested changes to slots and groups
  database/factories/SlotFactory.php
  database/migrations/2022_08_24_085124_create_slots_table.php
  database/migrations/2022_08_24_085154_create_groups_table.php
Labels: enhancement
