Repository fsr5-fhaachen/portals, pull requests merged in 2022-09, with the labels that each got.

#106 Implement patriks feedback
  .env.example
  .vscode/settings.json
  README.md
  app/Http/Controllers/AppController.php
  app/Http/Middleware/HandleInertiaRequests.php
  database/migrations/2022_08_24_084921_create_events_table.php
  database/migrations/2022_08_24_084934_create_pages_table.php
  resources/js/components/card/Container.vue
  resources/js/layouts/CardLayout.vue
  resources/js/pages/Dashboard/Event/Index.vue
  resources/js/pages/Dashboard/Page.vue
  resources/js/types/components.d.ts
  resources/js/types/models.d.ts
  tests/Feature/ExampleTest.php
Labels: enhancement

#121 change to https if env is production
  app/Providers/AppServiceProvider.php
Labels: enhancement

#122 Fix/json parse
  resources/js/pages/Dashboard/Event/Register.vue
Labels: bug

#123 fix timezone
  config/app.php
Labels: enhancement

#125 add unregister error messages
  app/Http/Controllers/DashboardEventController.php
Labels: enhancement

#129 Feat/scaleup
  scaleup/.env.example
  scaleup/README.md
  scaleup/hosts.ini
  scaleup/playbooks/update_hosts.yml
  scaleup/portals_scaleup.py
Labels: enhancement

#131 Feat/scaleup
  scaleup/.env.example
  scaleup/portals_scaleup.py
Labels: enhancement

#133 add db setup to ansible playbook
  scaleup/playbooks/update_hosts.yml
Labels: enhancement

#137 Feat/admin view
  resources/js/components/app/Navbar.vue
  resources/js/pages/Dashboard/Event/Register.vue
Labels: bug, enhancement

#139 Feat/admin view
  .env.example
  app/Http/Controllers/Api/ApiController.php
  app/Http/Controllers/DashboardAdminController.php
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/DashboardEventController.php
  config/app.php
  database/seeders/EventsSeeder.php
  resources/js/components/event/Card.vue
  resources/js/components/event/Table.vue
  resources/js/components/group/Table.vue
  resources/js/components/registration/Table.vue
  resources/js/components/slot/Table.vue
  resources/js/pages/Dashboard/Admin/Event.vue
  resources/js/pages/Dashboard/Admin/Submit.vue
  resources/js/pages/Dashboard/Event/Index.vue
  resources/js/pages/Dashboard/Index.vue
  routes/web.php
Labels: enhancement

#140 Fix display bug
  app/Http/Controllers/Api/ApiController.php
  app/Http/Controllers/DashboardEventController.php
  database/seeders/EventsSeeder.php
  resources/js/components/registration/Table.vue
Labels: enhancement

#143 Feat/maximum participants
  app/Helpers/GroupCourseDivision.php
  app/Helpers/GroupDivision.php
  app/Helpers/SlotAssignment.php
  app/Http/Controllers/Api/ApiController.php
  app/Http/Controllers/AppController.php
  app/Http/Controllers/DashboardAdminController.php
  app/Http/Controllers/DashboardEventController.php
  app/Http/Controllers/DashboardTutorController.php
  app/Http/Controllers/DivisionController.php
  database/factories/CourseFactory.php
  database/factories/GroupFactory.php
  resources/js/components/app/Navbar.vue
  resources/js/components/registration/Table.vue
  resources/js/composables/useSelectFormEventOptions.ts
  resources/js/composables/useSelectFormSlotOptions.ts
  resources/js/pages/Dashboard/Admin/Event.vue
  resources/js/pages/Dashboard/Admin/Register.vue
  resources/js/pages/Dashboard/Admin/Registrations.vue
  resources/js/pages/Dashboard/Admin/Submit.vue
  resources/js/pages/Dashboard/Tutor/Registrations.vue
  resources/js/types/auto-imports.d.ts
  routes/web.php
Labels: bug, enhancement

#144 Fix typo
  app/Http/Controllers/DashboardAdminController.php
Labels: bug

#145 Fix/typo
  app/Http/Controllers/DashboardAdminController.php
Labels: bug, enhancement

#146 Fix/typo
  app/Http/Controllers/DashboardAdminController.php
  app/Http/Controllers/DashboardEventController.php
  resources/js/pages/Dashboard/Admin/Submit.vue
Labels: bug, enhancement

#147 Fix/typo
  app/Http/Controllers/DashboardAdminController.php
  app/Http/Controllers/DashboardEventController.php
Labels: bug, enhancement

#148 Feat/simon feedback
  app/Http/Controllers/DashboardAdminController.php
  resources/js/pages/Dashboard/Event/Index.vue
Labels: bug, enhancement

#150 fix auto migrate and db seed
  scaleup/playbooks/update_hosts.yml
Labels: bug, enhancement

#151 Prepare 2.0.0
  README.md
  composer.json
  package-lock.json
  package.json
  vite.config.js
Labels: documentation, enhancement, breaking-change, dependencies

#153 Set default value for queuePosition
  app/Http/Controllers/DashboardAdminController.php
Labels: bug

#154 fix event data
  database/seeders/EventsSeeder.php
Labels: enhancement

#155 add page seeder and do fixes for release
  database/seeders/DatabaseSeeder.php
  database/seeders/EventsSeeder.php
  database/seeders/PageSeeder.php
  database/seeders/pages/faq.html
  resources/js/pages/Dashboard/Admin/Event.vue
Labels: bug, enhancement

#156 Add Stadtrallye and Kneipentour
  database/seeders/EventsSeeder.php
Labels: enhancement

#159 Fix/division
  app/Helpers/GroupBalancedDivision.php
  app/Helpers/GroupDivision.php
  app/Http/Controllers/DashboardAdminController.php
  app/Http/Controllers/DashboardEventController.php
Labels: bug, enhancement

#158 Fix/division algs fixes
  app/Helpers/GroupBalancedDivision.php
  app/Helpers/GroupCourseDivision.php
  app/Helpers/GroupDivision.php
  app/Http/Controllers/DashboardAdminController.php
  app/Http/Controllers/DashboardEventController.php
Labels: enhancement, breaking-change, php

#157 add event sort
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/DashboardTutorController.php
  database/factories/EventFactory.php
  database/migrations/2022_09_18_010736_add_sort_order_to_events_table.php
  database/seeders/EventsSeeder.php
Labels: enhancement

#163 Feat/stresstest seeder
  database/seeders/StresstestSeeder.php
Labels: enhancement, php

#164 null int conversion fix
  database/seeders/StresstestSeeder.php
Labels: bug, php

#167 add overview page and change ansible script
  database/seeders/PageSeeder.php
  database/seeders/pages/overview.html
  scaleup/hosts.ini
  scaleup/playbooks/update_hosts.yml
Labels: bug, enhancement, breaking-change

#162 Fix/titus
  resources/js/components/app/Navbar.vue
  resources/js/pages/Dashboard/Admin/Register.vue
Labels: bug, enhancement

#168 Improve load for production
  app/Http/Controllers/Api/ApiController.php
  resources/js/pages/Dashboard/Admin/Event.vue
  resources/js/pages/Dashboard/Admin/Registrations.vue
  resources/js/pages/Dashboard/Tutor/Event.vue
  resources/js/types/models.d.ts
  routes/web.php
Labels: enhancement

#160 change deployment to main branch
  scaleup/README.md
  scaleup/playbooks/update_hosts.yml
Labels: enhancement, breaking-change

#170 change sport and culture event registration
  database/seeders/EventsSeeder.php
Labels: bug, enhancement

#169 fix ansible variable
  scaleup/playbooks/update_hosts.yml
Labels: bug, enhancement

#171 change events and pages
  database/seeders/EventsSeeder.php
  database/seeders/pages/overview.html
Labels: bug, enhancement, breaking-change

#173 Added shuffle to assignInitial of slotassign and fixed Event factory bug
  app/Helpers/SlotAssignment.php
  database/factories/EventFactory.php
Labels: bug, enhancement, php

#174 fix event description
  database/seeders/EventsSeeder.php
Labels: enhancement

#175 fix overview
  database/seeders/pages/overview.html
Labels: bug, enhancement

#177 fix max participants
  database/seeders/EventsSeeder.php
Labels: bug, enhancement

#178 Add update feature
  database/seeders/PageSeeder.php
  database/seeders/pages/faq.html
Labels: bug, enhancement

#179 Try format fix
  app/Models/Event.php
Labels: bug

#183 fix scaleup script
  scaleup/portals_scaleup.py
Labels: bug, enhancement, breaking-change
