Repository fsr5-fhaachen/portals, pull requests merged in 2022-10, with the labels that each got.

#206 add docker
  .dockerignore
  .env.example
  .github/workflows/docker-dev.yml
  .github/workflows/docker-release.yml
  .gitignore
  Dockerfile
  README.md
  composer.json
  composer.lock
  config/octane.php
  docker-compose.yml
Labels: enhancement, github_actions

#208 remove build-args from docker-workflow
  .github/workflows/docker-dev.yml
  .github/workflows/docker-release.yml
Labels: bug, github_actions

#209 fix docker image name
  .github/workflows/docker-dev.yml
  .github/workflows/docker-release.yml
Labels: bug, github_actions

#248 add redis docker extension
  Dockerfile
Labels: bug, enhancement

#249 Feat/gerolstein
  .github/workflows/ci.yml
  app/Http/Controllers/AppController.php
  app/Http/Middleware/ActiveModule.php
  app/Models/Module.php
  database/migrations/2022_10_22_174738_create_modules_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/EventsErstiwocheSeeder.php
  database/seeders/EventsGerolsteinSeeder.php
  database/seeders/ModuleErstiwocheSeeder.php
  database/seeders/ModuleGerolsteinSeeder.php
  database/seeders/PageErstiwocheSeeder.php
  database/seeders/PageGerolsteinSeeder.php
  database/seeders/TutorSeeder.php
  database/seeders/pages/erstiwoche/.gitignore
  database/seeders/pages/erstiwoche/faq.html
  database/seeders/pages/erstiwoche/overview.html
  database/seeders/pages/gerolstein/.gitignore
  package-lock.json
  package.json
  resources/js/layouts/CardLayout.vue
  routes/web.php
Labels: enhancement, dependencies

#250 Feat/gerolstein
  database/seeders/DatabaseSeeder.php
  database/seeders/StudentSeeder.php
Labels: enhancement

#254 Last fixes for Gerolstein 2022
  .gitignore
  database/seeders/DatabaseSeeder.php
  database/seeders/EventsGerolsteinSeeder.php
  database/seeders/StudentSeeder.php
  database/seeders/TutorSeeder.php
Labels: bug, enhancement

#255 Release 2.1.0
  .dockerignore
  .env.example
  .github/workflows/ci.yml
  .github/workflows/docker-dev.yml
  .github/workflows/docker-release.yml
  .gitignore
  Dockerfile
  README.md
  app/Http/Controllers/AppController.php
  app/Http/Middleware/ActiveModule.php
  app/Models/Module.php
  composer.json
  composer.lock
  config/octane.php
  database/migrations/2022_10_22_174738_create_modules_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/EventsErstiwocheSeeder.php
  database/seeders/EventsGerolsteinSeeder.php
  database/seeders/ModuleErstiwocheSeeder.php
  database/seeders/ModuleGerolsteinSeeder.php
  database/seeders/PageErstiwocheSeeder.php
  database/seeders/PageGerolsteinSeeder.php
  database/seeders/StudentSeeder.php
  database/seeders/TutorSeeder.php
  database/seeders/pages/erstiwoche/.gitignore
  database/seeders/pages/erstiwoche/faq.html
  database/seeders/pages/erstiwoche/overview.html
  database/seeders/pages/gerolstein/.gitignore
  docker-compose.yml
  package-lock.json
  package.json
  resources/js/components/registration/Table.vue
  resources/js/layouts/CardLayout.vue
  routes/web.php
Labels: bug, documentation, enhancement, dependencies
