Repository fsr5-fhaachen/portals, pull requests merged in 2023-08, with the labels that each got.

#375 Implement multistage build
  .dockerignore
  .github/release.yml
  .github/workflows/docker-dev.yml
  .github/workflows/docker-release.yml
  Dockerfile
  docker-compose.yml
Labels: enhancement, github_actions

#379 fix(ci): docker release typo
  .github/workflows/docker-release.yml
Labels: bug, github_actions

#387 feat(config/database): add redis cluster support
  config/database.php
Labels: enhancement

#388 fix(ci/docker-release): add roadrunner dependencies
  .devcontainer/devcontainer.json
  composer.json
  composer.lock
Labels: bug, dependencies

#377 Add k8s support
  .dockerignore
  .github/workflows/release-chart.yml
  README.md
  charts/portals/Chart.yaml
  charts/portals/README.md
  charts/portals/templates/_helpers.tpl
  charts/portals/templates/deployment.yaml
  charts/portals/templates/ingress.yaml
  charts/portals/templates/secret.yaml
  charts/portals/templates/service.yaml
  charts/portals/values.yaml
  deploy/README.md
  deploy/cluster/cluster.yaml
  deploy/cluster/hetznercluster.yaml
  deploy/cluster/kubeadm-cfg-tmpl.yaml
  deploy/cluster/kubeadm-ctl.yaml
  deploy/cluster/machine-tmpl.yaml
  deploy/cluster/md.yaml
  deploy/cluster/secret.yaml
  deploy/deployments/addons/ccm-secret.yaml
  deploy/deployments/addons/ccm-values.yaml
  deploy/deployments/addons/cert-manager-issuer.yaml
  deploy/deployments/addons/cert-manager-values.yaml
  deploy/deployments/addons/cilium-values.yaml
  deploy/deployments/addons/csi-2.7.0.yaml
  deploy/deployments/addons/csi-secret.yaml
  deploy/deployments/addons/ingress-nginx-values.yaml
  deploy/deployments/portals/pgsql.yaml
  deploy/deployments/portals/portals-values.yaml
  deploy/deployments/portals/redis-pw-secret.yaml
  deploy/deployments/portals/redis-values.yaml
  deploy/nat-gateway/cloud-config.yaml
  scaleup/.env.example
  scaleup/README.md
  scaleup/hosts.ini
  scaleup/playbooks/update_hosts.yml
  scaleup/portals_scaleup.py
Labels: enhancement

#397 Implement new features
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  database/migrations/2023_08_24_202037_add_show_on_registration_to_courses.php
  database/migrations/2023_08_24_220331_migrate_color_to_classes_in_courses.php
  database/seeders/CourseSeeder.php
  database/seeders/DatabaseSeeder.php
  package-lock.json
  package.json
  public/images/hetzner.png
  resources/js/App.vue
  resources/js/app.js
  resources/js/components/app/Button.vue
  resources/js/components/app/Link.vue
  resources/js/components/app/Navbar.vue
  resources/js/components/card/Base.vue
  resources/js/components/color/mode/Button.vue
  resources/js/components/course/Box.vue
  resources/js/components/event/Card.vue
  resources/js/components/event/Table.vue
  resources/js/components/form/Divider.vue
  resources/js/components/group/Table.vue
  resources/js/components/registration/Table.vue
  resources/js/components/slot/Table.vue
  resources/js/components/ui/Dd.vue
  resources/js/components/ui/Dt.vue
  resources/js/components/ui/H1.vue
  resources/js/components/ui/H2.vue
  resources/js/components/ui/Message.vue
  resources/js/composables/useColorMode.ts
  resources/js/composables/useSelectFormCourseOptions.ts
  resources/js/formkit.theme.ts
  resources/js/layouts/CardLayout.vue
  resources/js/layouts/DashboardCardLayout.vue
  resources/js/layouts/DashboardLayout.vue
  resources/js/pages/Dashboard/Admin/Index.vue
  resources/js/pages/Dashboard/Admin/Register.vue
  resources/js/pages/Dashboard/Event/Index.vue
  resources/js/pages/Dashboard/Event/Register.vue
  resources/js/pages/Dashboard/Page.vue
  resources/js/types/auto-imports.d.ts
  resources/js/types/components.d.ts
  resources/js/types/models.d.ts
  resources/views/app.blade.php
  tailwind.config.js
  vite.config.js
Labels: enhancement, breaking-change, dependencies

#404 fix(ci): helm chart release action version
  .github/workflows/release-chart.yml
Labels: bug, github_actions

#405 fix(ci): helm chart release action version (#404)
  .github/workflows/release-chart.yml
Labels: bug, github_actions

#406 fix(ci): helm chart release
  .github/workflows/release-chart.yml
Labels: bug, github_actions

#407 fix(ci): helm chart release
  .github/workflows/release-chart.yml
  composer.lock
  package-lock.json
  package.json
Labels: bug, github_actions

#408 move(charts): move helm chart to charts repo
  .github/workflows/release-chart.yml
  README.md
  charts/portals/Chart.yaml
  charts/portals/README.md
  charts/portals/templates/_helpers.tpl
  charts/portals/templates/deployment.yaml
  charts/portals/templates/ingress.yaml
  charts/portals/templates/secret.yaml
  charts/portals/templates/service.yaml
  charts/portals/values.yaml
  deploy/README.md
Labels: deprecated, github_actions

#433 fix: redis
  .env.example
  composer.json
  composer.lock
  config/database.php
Labels: bug

#431 Added DIB Course to CourseSeeder
  database/seeders/CourseSeeder.php
Labels: enhancement

#435 fix(redis): switch to cluster instead of sentinel
  .env.example
  composer.json
  composer.lock
  config/database.php
Labels: bug

#436 fix: redis and docker
  Dockerfile
  config/database.php
Labels: bug, enhancement
