Repository fsr5-fhaachen/portals, pull requests merged in 2023-09, with the labels that each got.

#441 Feat/bonobos to pandas and add missing icon
  database/seeders/CourseSeeder.php
  database/seeders/EventsErstiwocheSeeder.php
  resources/js/app.js
Labels: bug, enhancement

#438 feat(deploy): enhance guide
  .gitignore
  deploy/README.md
  deploy/cluster/cluster.yaml
  deploy/deployments/addons/cert-manager-issuer.yaml
  deploy/deployments/portals/pgsql.yaml
  deploy/deployments/portals/portals-values.yaml
  deploy/deployments/portals/redis-values.yaml
Labels: documentation, enhancement

#458 Add missing import
  resources/js/layouts/CardLayout.vue
Labels: bug

#459 Fix dark mode bugs
  resources/js/formkit.theme.ts
  resources/js/pages/Dashboard/Admin/Event.vue
Labels: bug

#456 Feat/cleanup
  app/Http/Controllers/CourseController.php
  app/Http/Controllers/DatabaseTestController.php
  app/Http/Controllers/DivisionController.php
  app/Http/Controllers/EventController.php
  app/Http/Controllers/GroupController.php
  app/Http/Controllers/GroupTutorController.php
  app/Http/Controllers/PageController.php
  app/Http/Controllers/RegistrationController.php
  app/Http/Controllers/SlotController.php
  app/Http/Controllers/StationController.php
  app/Http/Controllers/StationTutorController.php
  app/Http/Controllers/StopController.php
  app/Http/Controllers/UserController.php
  database/seeders/EventSeeder.php
  database/seeders/GroupCourseDivisionTestSeeder.php
  database/seeders/GroupSeeder.php
  database/seeders/GroupTutorSeeder.php
  database/seeders/RegistrationSeeder.php
  database/seeders/SlotAssignmentSeeder.php
  database/seeders/SlotSeeder.php
  database/seeders/StationSeeder.php
  database/seeders/StationTutorSeeder.php
  database/seeders/StopSeeder.php
  database/seeders/StresstestSeeder.php
  database/seeders/UserSeeder.php
  routes/web.php
Labels: enhancement

#457 Feat/assignment testing
  .env.example
  app/Helpers/DivisionLogger.php
  app/Helpers/GroupBalancedDivision.php
  app/Helpers/GroupCourseDivision.php
  app/Helpers/GroupDivision.php
  app/Http/Controllers/DivisionLoggingController.php
  config/database.php
  database/seeders/TestingSeeder.php
  routes/web.php
Labels: enhancement

#445 feat(deploy): enhance values and add monitoring
  deploy/README.md
  deploy/deployments/addons/cilium-pod-monitor.yaml
  deploy/deployments/addons/cilium-values.yaml
  deploy/deployments/addons/ingress-nginx-values.yaml
  deploy/deployments/addons/pgsql-operator-pod-monitor.yaml
  deploy/deployments/addons/prometheus-values.yaml
  deploy/deployments/portals/pgsql.yaml
  deploy/deployments/portals/portals-values.yaml
Labels: enhancement

#468 Feat/add more demo seeder
  app/Helpers/DivisionLogger.php
  app/Helpers/GroupBalancedDivision.php
  app/Helpers/GroupCourseDivision.php
  app/Helpers/GroupDivision.php
  app/Http/Controllers/DivisionLoggingController.php
  app/Providers/RouteServiceProvider.php
  config/database.php
  database/seeders/DatabaseSeeder.php
  database/seeders/EventsDemoSeeder.php
  database/seeders/UserDemoSeeder.php
  routes/web.php
Labels: enhancement

#472 Add group_phase_by_course
  app/Models/Course.php
  app/Models/Event.php
  app/Models/Group.php
  app/Models/GroupTutor.php
  app/Models/Page.php
  app/Models/Registration.php
  app/Models/Slot.php
  app/Models/Station.php
  app/Models/StationTutor.php
  app/Models/Stop.php
  app/Models/User.php
  database/seeders/EventsDemoSeeder.php
  resources/js/pages/Dashboard/Admin/Submit.vue
Labels: enhancement

#473 feat(deploy): move to one zone and bigger servers
  deploy/README.md
  deploy/cluster/hetznercluster.yaml
  deploy/cluster/machine-tmpl.yaml
  deploy/cluster/md.yaml
  deploy/deployments/addons/ingress-nginx-values.yaml
Labels: enhancement

#474 feat(github_actions): add delete untagged images ci
  .github/workflows/docker-cleanup.yaml
Labels: enhancement, github_actions

#442 Feat/prepare erstiwoche
  database/seeders/EventsErstiwocheSeeder.php
  database/seeders/PageErstiwocheSeeder.php
  database/seeders/pages/erstiwoche/faq.html
  database/seeders/pages/erstiwoche/overview.html
  database/seeders/pages/erstiwoche/videos.html
  resources/js/components/app/Navbar.vue
  resources/js/components/event/Table.vue
  resources/js/components/group/Table.vue
  resources/js/components/slot/Table.vue
  resources/js/pages/Dashboard/Admin/Event.vue
  resources/js/pages/Dashboard/Admin/Index.vue
  resources/js/pages/Dashboard/Admin/Registrations.vue
  resources/js/pages/Dashboard/Event/Index.vue
  resources/js/pages/Dashboard/Tutor/Event.vue
  resources/js/pages/Dashboard/Tutor/Group.vue
  resources/js/pages/Dashboard/Tutor/Slot.vue
Labels: enhancement
