Repository fsr5-fhaachen/portals, pull requests merged in 2023-10, with the labels that each got.

#514 feat: add support for user images via S3
  app/Http/Controllers/DashboardAdminController.php
  app/Http/Controllers/DashboardAdminRandomGeneratorController.php
  composer.json
  composer.lock
  config/app.php
  package-lock.json
  resources/js/formkit.theme.ts
  resources/js/pages/Dashboard/Admin/Register.vue
Labels: enhancement

#506 fix(readme): kubernetes link
  README.md
Labels: bug, documentation

#507 feat(readme): add devcontainer section
  README.md
Labels: documentation, enhancement

#508 feat(deploy): add aws s3
  deploy/README.md
Labels: documentation, enhancement

#513 feat(github_actions): add docker e2e test
  .devcontainer/devcontainer.json
  .github/workflows/docker-e2e.yaml
  docker-compose.sail.yaml
  docker-compose.yaml
Labels: enhancement, github_actions

#519 update(docker): roadrunner
  Dockerfile
Labels: enhancement

#520 fix(database/seeders): invalid and missing seeders
  database/seeders/DatabaseSeeder.php
  database/seeders/TutorSeeder.php
Labels: bug, enhancement

#521 feat(database/seeders/tutor): switch delimiter and add disabled
  database/seeders/TutorSeeder.php
Labels: enhancement

#533 Fix/darkmode
  database/seeders/TutorSeeder.php
  resources/js/components/user/EditModal.vue
Labels: bug

#432 Feat/update authors in readme md #335
  README.md
Labels: documentation, enhancement

#537 Changed Gif
  resources/js/pages/Dashboard/Admin/RandomGenerator/Display.vue
Labels: bug

#538 Feat/improve audio
  resources/js/pages/Dashboard/Admin/RandomGenerator/Display.vue
  resources/js/types/components.d.ts
Labels: enhancement

#539 Update event data
  database/seeders/EventsGerolsteinSeeder.php
Labels: enhancement
