Repository fsr5-fhaachen/portals, pull requests merged in 2024-10, with the labels that each got.

#738 fix: hotfix erstiwoche 2024
  app/Http/Controllers/DashboardAdminController.php
  database/seeders/EventsErstiwocheSeeder.php
Labels: bug

#763 feat: add sound to score-system
  public/sounds/score-system/final-fantasy-level-up-27603.mp3
  public/sounds/score-system/fire-emblem-level-up.mp3
  public/sounds/score-system/hp-level-up-mario-4253.mp3
  public/sounds/score-system/mc-level-up-13367.mp3
  resources/js/pages/Dashboard/Admin/ScoreSystem/Display.vue
Labels: enhancement, javascript

#776 feat: add expose_public to modules
  app/Http/Middleware/ActivePublicModule.php
  database/migrations/2024_10_07_055750_add_expose_public_to_modules_table.php
  database/seeders/ModuleDemoSeeder.php
  database/seeders/ModuleErstiwocheSeeder.php
  database/seeders/ModuleGerolsteinSeeder.php
  database/seeders/ModuleSeeder.php
  routes/web.php
Labels: enhancement, php

#800 fix: public modules
  app/Http/Controllers/Api/ApiController.php
  app/Http/Controllers/DashboardAdminCountdownController.php
  composer.lock
  docker-compose.sail.yaml
  package-lock.json
  resources/js/layouts/DisplayLayout.vue
  resources/js/pages/Dashboard/Admin/Countdown/Display.vue
  resources/js/pages/Dashboard/Admin/Countdown/Index.vue
  resources/js/pages/Dashboard/Admin/RandomGenerator/Display.vue
  resources/js/pages/Dashboard/Admin/ScoreSystem/Display.vue
  resources/js/types/auto-imports.d.ts
  routes/web.php
  vite.config.js
Labels: bug

#793 fix login email being case-sensitive
  app/Http/Controllers/AppController.php
  database/migrations/2024_10_16_150540_convert_email_to_lowercase.php
  database/seeders/StudentSeeder.php
  database/seeders/TutorSeeder.php
Labels: bug, php

#811 Feat/prepare gerolstein 2024
  database/seeders/EventsGerolsteinSeeder.php
Labels: enhancement
