Repository fsr5-fhaachen/portals, pull requests merged in 2024-09, with the labels that each got.

#698 fix: prod deployment
  app/Http/Controllers/DashboardController.php
  config/database.php
Labels: bug

#666 feat: use presigned urls for s3
  app/Http/Controllers/Api/ApiController.php
  app/Http/Controllers/DashboardAdminController.php
  app/Models/User.php
  resources/js/components/user/EditModal.vue
  resources/js/composables/useS3.ts
  resources/js/pages/Dashboard/Admin/Register.vue
  resources/js/types/auto-imports.d.ts
  resources/js/types/group.d.ts
  routes/web.php
Labels: enhancement, php

#661 feat: telegram group links
  database/migrations/2024_08_19_142538_add_telegram_group_link_to_groups_table.php
  database/migrations/2024_08_20_091921_add_telegram_group_link_to_slots_table.php
  database/seeders/EventsDemoSeeder.php
  database/seeders/EventsErstiwocheSeeder.php
  database/seeders/tutors.csv.example
  resources/js/components/ui/Message.vue
  resources/js/pages/Dashboard/Event/Index.vue
  resources/js/pages/Dashboard/Tutor/Group.vue
  resources/js/pages/Dashboard/Tutor/Slot.vue
Labels: enhancement, php, javascript

#670 feat: use frankenphp
  .env.example
  .gitignore
  Dockerfile
  composer.lock
  config/octane.php
  docker-compose.sail.yaml
Labels: enhancement

#700 feat: add INF and IS master
  database/seeders/CourseSeeder.php
  resources/js/app.js
Labels: enhancement

#646 feat: add admin option to assign user to group
  app/Http/Controllers/DashboardAdminController.php
  resources/js/composables/useSelectFormGroupOptions.ts
  resources/js/pages/Dashboard/Admin/Register.vue
  resources/js/types/auto-imports.d.ts
Labels: enhancement

#673 feat: add BelongsToMany relation to group courses
  app/Helpers/GroupCourseDivision.php
  app/Http/Controllers/DashboardAdminController.php
  app/Http/Controllers/DashboardTutorController.php
  app/Models/Course.php
  app/Models/CourseGroup.php
  app/Models/Group.php
  database/migrations/2024_09_08_212424_create_course_group_table.php
  database/seeders/EventsDemoSeeder.php
  database/seeders/EventsErstiwocheSeeder.php
  resources/js/components/group/Table.vue
  resources/js/pages/Dashboard/Admin/Event.vue
  resources/js/pages/Dashboard/Admin/Submit.vue
  resources/js/pages/Dashboard/Tutor/Event.vue
  resources/js/pages/Dashboard/Tutor/Group.vue
  resources/js/types/course-group.d.ts
  resources/js/types/group.d.ts
  resources/js/types/slot.d.ts
Labels: enhancement

#720 feat: add course event relation
  app/Http/Controllers/DashboardController.php
  app/Http/Controllers/DashboardEventController.php
  app/Http/Controllers/DashboardTutorController.php
  app/Models/CourseEvent.php
  app/Models/Event.php
  database/migrations/2024_09_15_084701_create_course_event_table.php
  database/seeders/EventsDemoSeeder.php
  database/seeders/EventsErstiwocheSeeder.php
  resources/js/components/event/Table.vue
  resources/js/pages/Dashboard/Index.vue
  resources/js/types/course-event.d.ts
  resources/js/types/event.d.ts
Labels: enhancement

#719 Feat/pages update
  database/seeders/PageErstiwocheSeeder.php
  database/seeders/pages/erstiwoche/faq.html
  database/seeders/pages/erstiwoche/overview.html
  database/seeders/pages/erstiwoche/videos.html
Labels: enhancement

#699 Content updates for the 2024 year
  .gitignore
  database/seeders/EventsErstiwocheSeeder.php
  database/seeders/telegram.csv.example
  resources/js/pages/Dashboard/Admin/Event.vue
  resources/js/pages/Dashboard/Tutor/Group.vue
  resources/js/pages/Dashboard/Tutor/Slot.vue
Labels: enhancement

#721 feat: update dependencies
  composer.lock
Labels: dependencies
